config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :entities
  end
  
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
  end
  
  devise_for :users
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :entities, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 60 }
  validates :icon, presence: true

  def self.default_icon
    'fas fa-question-circle'
  end

  def total_transactions
    entities.where(category_id: id).sum(:amount).to_f
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category, class_name: 'Category', foreign_key: 'category_id'

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 60 }
  validates :amount, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10**5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :entities, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 60 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(*)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.where(author_id: current_user.id).order(created_at: :desc) || []
  end

  def show
    @categories = Category.includes(:entities).find(params[:id])
    @entities = @category.entities.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to categories_path, notice: 'Category was successfully destroyed.' }
      else
        format.html { redirect_to categories_path, alert: 'Category was not destroyed.' }
      end
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @category = Category.find(params[:category_id])
    @entities = Entity.where(category_id: @category.id).order('created_at DESC')
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
    @categories = Category.where(author_id: current_user.id) || []
    @category_id = params[:category_id].to_i
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id
    @entity.category_id = params[:category_id].to_i

    respond_to do |format|
      if @entity.save
        format.html do
          redirect_to category_entities_path,
                      notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /entities/1/edit
  def edit; end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :category_id, category_ids: []).merge(author_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class = "app_header">
  <h2> CARTEGORIES </h2>
  <a href = "/logout" id = "logout">Logout</a>
</div>

<div class="categories">
    <% if @categories.nil? || @categories.empty? %>
        <div class="no-record">
            <p>No Record in the Database.</p>
            <p> Please Add a Category</p>
        </div>
    <% else %>
        <% @categories.each do |category| %>
            <div class = "category">
                <%= link_to category_entities_path(category.id) do %>
                    <% def valid_image_url?(url) %>
                        <% url.present? && url =~ /\Ahttps?:\/\/\S+\z/ %>
                    <% end %>

                    <% if valid_image_url?(category.icon) %>
                        <%= image_tag category.icon, alt: 'Category image' %>
                    <% else %>
                        <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJcT7PQqrhP-fcTi2K3UTvx1CZMmLvFPvupUZivUCJMFDRsX4LxhTRuenl5VHpbhs7elI&usqp=CAU', alt: 'My Image' %>
                    <% end %>
                <% end %>
        
                <div class="category-details">
                    <%= link_to category.name.capitalize, category_entities_path(category.id) %>
                    <span> Total: <%= category.total_transactions%>$ </span>
                </div>
            </div>
        <% end %>
    <% end %>
</div>
<div class ="footer">
    <i class="fa-solid fa-plus"></i>
    <%= link_to 'Add Category', new_category_path, class: "footer_link" %>
</div>

app/views/categories/new.html.erb
<div class = "app_header">
    <a href="<%= categories_path %>">
        <i class="fa-solid fa-arrow-left" id = "left-arrow"></i>
    </a>
    <h2>New Category</h2>
    <a href="/logout" id = "logout">
        Logout
    </a>
</div>

<div class= "form-container">
    <%= form_with(model: @category, url: categories_path) do |form| %>
        <div class = "form-element">
            <%= form.text_field :name, placeholder: "Name" %>
            <% if @category.errors.any? %>
                <span class="alert">
                    <%= @category.errors[:name].first %>
                </span>
            <% end %>
        </div>

        <div class = "form-element">
            <%= form.text_field :icon, placeholder: "Icon Link" %>
            <% if @category.errors.any? %>
                <span class="alert">
                    <%= @category.errors[:icon].first %>
                </span>
            <% end %>
        </div>

        <%= form.submit "Save", class: "submit-button" %>
    <% end %>
</div>

app/views/categories/show.html.erb
<%= link_to "Back", categories_path%>

<% render @category%>

<div>
  <%= link_to, edit_category_path(@category)%>
  <% link_to "Destroy", @category, method: :delete %>
</div>

app/views/entities/index.html.erb
<div class = "app_header">
  <a href= "<%= categories_path %>">
    <i class="fa-solid fa-arrow-left" id = "left-arrow"></i>
  </a>
  <h2> Transactions</h2>
  <a href = "/logout" id = "logout">Logout</a>
</div>

<div class="categories">
  <% if @entities.nil? || @entities.empty?%>
      <div class="no-record">
        <p>No Transaction for this Category. </p>
        <p>Please Add a Transaction</p>
      </div>
  <% else %>
      <div class="total-amount">
        <p>Total: <%= @category.total_transactions%>$</p>
      </div>
      
      <% @entities.each do |entity| %>
        <div class = "transaction" >
          <p><%= entity.name %></p>
          <p>Price: <%= entity.amount %>$ </p>
        </div>
      <% end %>
  <% end %>
</div>

<div class ="footer">
    <i class="fa-solid fa-plus"></i>
    <%= link_to 'New Transaction', new_category_entity_path, class: "footer_link" %>
</div>

app/views/entities/new.html.erb
<%= form_with(model: @entity, url: category_entities_path) do |form| %>
    <div class = "app_header">
        <a href ="<%= category_entities_path %>">
            <i class="fa-solid fa-arrow-left" id="left-arrow"></i>
        </a>
        <p> New Transaction </p>
        <a href="/logout" id = "logout" >
            Logout
        </a>
    </div>

    <div class = "form-container">
        <div class="field">
            <%= form.text_field :name, placeholder: "Name "%>
            <% if @entity.errors.any? %>
                <span class="alert">
                    <%= @entity.errors[:name].first %>
                </span>
            <% end %>
        </div>

        <div class="field">
            <%= form.text_field :amount, placeholder: "Price "%>
            <% if @entity.errors.any? %>
                <span class="alert">
                    <%= @entity.errors[:amount].first %>
                </span>
            <% end %>
        </div>

        <%= form.submit "Save", class: "submit-button" %>
    </div>
<% end %>

app/views/entities/show.html.erb
<%= render @payment %>

<div>
  <%= link_to "Edit", edit_payment_path(@payment) %> |
  <%= link_to "Back", payments_path %>

  <%= button_to "Destroy", @payment, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="container">
    <h1 class="title">Budget Tracker App</h1>
    <div class="auth-btns">
        <%= link_to "Log In" , new_user_session_path, class: "signin" %>
        <%= link_to "Sign Up" , new_user_registration_path, class: "signup" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = "container">
      <%= yield %>
    </div>

    <script src="https://kit.fontawesome.com/59b66b3fc6.js" crossorigin="anonymous"></script>
  </body>
</html>